FROM node:20.19.0-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma
RUN npm install

COPY . .

CMD ["sh", "-c", "npm run migrate:deploy && npm run start:dev"]
