services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fedyabot-app:latest
    container_name: fedyabot-app
    restart: always
    env_file:
      - .env.prod
    environment:
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # For connecting to external DB/Nginx on host
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "outline.rilokobotfactory3.ru:host-gateway"
      - "fedyabot.rilokobotfactory3.ru:host-gateway"
      - "api.telegram.org:149.154.167.220"
    ports:
      - "7000:3000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2.4-alpine
    container_name: fedyabot-redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
