-- CreateTable
CREATE TABLE `AnalyticsEvents` (
    `id` VARCHAR(191) NOT NULL,
    `dedupeKey` VARCHAR(191) NOT NULL,
    `source` VARCHAR(191) NOT NULL DEFAULT 'runtime',
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `type` VARCHAR(191) NOT NULL,
    `action` VARCHAR(191) NULL,
    `stage` VARCHAR(191) NULL,
    `integration` VARCHAR(191) NULL,
    `method` VARCHAR(191) NULL,
    `status` INTEGER NULL,
    `state` VARCHAR(191) NULL,
    `error` LONGTEXT NULL,
    `text` LONGTEXT NULL,
    `callbackData` VARCHAR(191) NULL,
    `tokens` DOUBLE NULL,
    `requestBody` JSON NULL,
    `responseBody` JSON NULL,
    `metadata` JSON NULL,
    `raw` JSON NOT NULL,
    `telegramId` VARCHAR(191) NULL,
    `username` VARCHAR(191) NULL,
    `firstName` VARCHAR(191) NULL,
    `lastName` VARCHAR(191) NULL,
    `chatId` VARCHAR(191) NULL,
    `userId` VARCHAR(191) NULL,
    `sessionId` VARCHAR(191) NULL,
    `articleId` VARCHAR(191) NULL,
    `articleTitle` TEXT NULL,
    `scenarioId` VARCHAR(191) NULL,

    UNIQUE INDEX `AnalyticsEvents_dedupeKey_key`(`dedupeKey`),
    INDEX `AnalyticsEvent_occurredAt_idx`(`occurredAt`),
    INDEX `AnalyticsEvent_type_idx`(`type`),
    INDEX `AnalyticsEvent_stage_idx`(`stage`),
    INDEX `AnalyticsEvent_userId_occurredAt_idx`(`userId`, `occurredAt`),
    INDEX `AnalyticsEvent_sessionId_occurredAt_idx`(`sessionId`, `occurredAt`),
    INDEX `AnalyticsEvent_articleId_occurredAt_idx`(`articleId`, `occurredAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

